language: php
dist: trusty
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm-nightly
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly
install:
  - composer install
before_script:
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
