language: php
dist: trusty
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm-3.24
  - hhvm-nightly
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-3.24
    - php: hhvm-nightly
install:
  - |
    php -v
    composer install
before_script:
  - |
    echo "TRAVIS_PHP_VERSION:" $TRAVIS_PHP_VERSION;
    if [ ${TRAVIS_PHP_VERSION:0:4} == "hhvm" ]; then
      #hhvm -d hhvm.php7.all=1;
      #curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-7.0.phar;
      curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar;
    else
      curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar;
    fi
